name: ongkoskirimapps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  introduction_screen: 3.0.2
  lottie: 1.3.0
  animated_splash_screen: 1.2.0
  dropdown_search: 3.0.1
  dio: 4.0.6
  loading_animations: 2.2.0
  http: 0.13.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lotties/
  uses-material-design: true

